USE ImovelNet

SELECT a.CDIMOVEL, b.CDVENDEDOR, b.NMVENDEDOR, a.SGESTADO
FROM IMOVEL a, VENDEDOR b
WHERE  a.CDVENDEDOR = B.CDVENDEDOR

SELECT a.CDCOMPRADOR, a.NMCOMPRADOR, b.CDIMOVEL, B.VLOFERTA
FROM COMPRADOR a, OFERTA b 
WHERE a.CDCOMPRADOR = b.CDCOMPRADOR

SELECT a.CDIMOVEL, a.VLPRECO, b.NMBAIRRO
FROM IMOVEL a, BAIRRO b 
WHERE a.CDVENDEDOR = 3
AND a.CDBAIRRO = b.CDBAIRRO
AND a.CDCIDADE = b.CDCIDADE
AND a.SGESTADO = b.SGESTADO

SELECT DISTINCT a.CDIMOVEL
FROM IMOVEL a INNER JOIN OFERTA b
ON a.CDIMOVEL = b.CDIMOVEL

SELECT a.CDIMOVEL, b.VLOFERTA
FROM IMOVEL a
LEFT JOIN OFERTA b
ON a.CDIMOVEL = b.CDIMOVEL;

SELECT a.CDCOMPRADOR, a.NMCOMPRADOR, B.VLOFERTA 
FROM COMPRADOR a, OFERTA b
WHERE a.CDCOMPRADOR = b.CDCOMPRADOR


SELECT a.CDCOMPRADOR, a.NMCOMPRADOR, B.VLOFERTA 
FROM COMPRADOR a LEFT JOIN OFERTA b
ON a.CDCOMPRADOR = b.CDCOMPRADOR

SELECT a.NMEDERECO, a.CDIMOVEL, b.NMEDERECO IMOVEL_INDICADO
FROM IMOVEL a, IMOVEL b 
WHERE a.IMOVEL_INDICADO = b.CDIMOVEL


SELECT a.NMEDERECO, a.CDIMOVEL, b.NMEDERECO IMOVEL_INDICADO, c.NMVENDEDOR, d.NMVENDEDOR IMOVEL_INDICADO_VENDEDOR
FROM IMOVEL a, IMOVEL b, VENDEDOR c, VENDEDOR d
WHERE a.IMOVEL_INDICADO = b.CDIMOVEL
AND a.CDVENDEDOR = c.CDVENDEDOR
AND b.CDVENDEDOR = d.CDVENDEDOR

SELECT a.NMEDERECO, b.NMBAIRRO, c.NMFAIXA
FROM IMOVEL a, BAIRRO b, FAIXA_IMOVEL c
WHERE a.VLPRECO BETWEEN c.VLMINIMO AND c.VLMAXIMO AND 
a.CDBAIRRO = b.CDBAIRRO AND
a.CDCIDADE = b.CDCIDADE AND
a.SGESTADO = b.SGESTADO
