--Usando o banco de dados criado (ImovelNet)
USE ImovelNet

--Incluindo um tuplas nas entidades
INSERT INTO ESTADO (SGESTADO, NMESTADO)
    VALUES('SP', 'SÃO PAULO');

INSERT INTO ESTADO (SGESTADO, NMESTADO)
    VALUES('RJ', 'RIO DE JANEIRO');

INSERT INTO CIDADE(CDCIDADE, NMCIDADE, SGESTADO)
    VALUES(1, 'S�O PAULO', 'SP');

INSERT INTO CIDADE(CDCIDADE, NMCIDADE, SGESTADO)
    VALUES(2, 'SANTO ANDR�', 'SP');

INSERT INTO CIDADE(CDCIDADE, NMCIDADE, SGESTADO)
    VALUES(3, 'CAMPINAS', 'SP');

INSERT INTO CIDADE(CDCIDADE, NMCIDADE, SGESTADO)
    VALUES(1, 'RIO DE JANEIRO', 'RJ');

INSERT INTO CIDADE(CDCIDADE, NMCIDADE, SGESTADO)
    VALUES(2, 'NITER�I', 'RJ');

INSERT INTO BAIRRO(CDBAIRRO, NMBAIRRO, CDCIDADE, SGESTADO)
    VALUES(1, 'JARDINS', 1, 'SP');

INSERT INTO BAIRRO(CDBAIRRO, NMBAIRRO, CDCIDADE, SGESTADO)
    VALUES(2, 'MORUMBI', 1, 'SP');

INSERT INTO BAIRRO(CDBAIRRO, NMBAIRRO, CDCIDADE, SGESTADO)
    VALUES(3, 'AEROPORTO', 1, 'SP');

INSERT INTO BAIRRO(CDBAIRRO, NMBAIRRO, CDCIDADE, SGESTADO)
    VALUES(1, 'AEROPORTO', 1, 'RJ');

INSERT INTO BAIRRO(CDBAIRRO, NMBAIRRO, CDCIDADE, SGESTADO)
    VALUES(2, 'FLAMENGO', 1, 'RJ');

INSERT INTO VENDEDOR(CDVENDEDOR, NMVENDEDOR, NMENDERECO, EMAIL)
    VALUES(1, 'MARIA DA SILVA', 'RUA DO GRITO, 45', 'msilva@novatec.com.br');

INSERT INTO VENDEDOR(CDVENDEDOR, NMVENDEDOR, NMENDERECO, EMAIL)
    VALUES(2, 'MARCOS ANDRADE', 'AV SAUDADE, 325', 'mandrade@novatec.com.br');

INSERT INTO VENDEDOR(CDVENDEDOR, NMVENDEDOR, NMENDERECO, EMAIL)
    VALUES(3, 'ANDRE CARDOSO', 'AV BRASIL, 401', 'acardoso@novatec.com.br');

INSERT INTO VENDEDOR(CDVENDEDOR, NMVENDEDOR, NMENDERECO, EMAIL)
    VALUES(4, 'TATIANA SOUZA', 'RUA DO IMPERADOR, 778', 'tsouza@novatec.com.br');

INSERT INTO IMOVEL(CDIMOVEL, CDVENDEDOR, CDBAIRRO, CDCIDADE, SGESTADO, NMEDERECO, NRAREAUTIL, 
NRAREATOTAL, VLPRECO, IMOVEL_INDICADO)
    VALUES(1, 1, 1, 1, 'SP', 'AL TIETE, 3304 AP 101', 250, 400, 180000, NULL );

INSERT INTO IMOVEL(CDIMOVEL, CDVENDEDOR, CDBAIRRO, CDCIDADE, SGESTADO, NMEDERECO, NRAREAUTIL, 
NRAREATOTAL, VLPRECO, IMOVEL_INDICADO)
    VALUES(2, 1, 2, 1, 'SP', 'AV MORUMBI, 2230', 150, 250, 135000, 1);

INSERT INTO IMOVEL(CDIMOVEL, CDVENDEDOR, CDBAIRRO, CDCIDADE, SGESTADO, NMEDERECO, NRAREAUTIL, 
NRAREATOTAL, VLPRECO, IMOVEL_INDICADO)
    VALUES(3, 2, 1, 1, 'RJ', 'R GAL OSORIO, 455 AP 34', 250, 400, 185000, 2);

INSERT INTO IMOVEL(CDIMOVEL, CDVENDEDOR, CDBAIRRO, CDCIDADE, SGESTADO, NMEDERECO, NRAREAUTIL, 
NRAREATOTAL, VLPRECO, IMOVEL_INDICADO)
    VALUES(4, 2, 2, 1, 'RJ', 'R D PEDRO I, 882', 120, 200, 110000, 1);

INSERT INTO IMOVEL(CDIMOVEL, CDVENDEDOR, CDBAIRRO, CDCIDADE, SGESTADO, NMEDERECO, NRAREAUTIL, 
NRAREATOTAL, VLPRECO, IMOVEL_INDICADO)
    VALUES(5, 3, 3, 1, 'SP', 'AV RUBEM BERTA, 2355', 110, 200, 95000, 4);

INSERT INTO IMOVEL(CDIMOVEL, CDVENDEDOR, CDBAIRRO, CDCIDADE, SGESTADO, NMEDERECO, NRAREAUTIL, 
NRAREATOTAL, VLPRECO, IMOVEL_INDICADO)
    VALUES(6, 4, 1, 1, 'RJ', 'R GETULIO VARGAS, 552 ', 200, 300, 99000, 5);

INSERT INTO COMPRADOR(CDCOMPRADOR, NMCOMPRADOR, NMENDERECO, EMAIL)
    VALUES(1, 'EMANUEL ANTUNES', 'R SARAIVA, 452', 'eantunes@novatec.com.br');

INSERT INTO COMPRADOR(CDCOMPRADOR, NMCOMPRADOR, NMENDERECO, EMAIL)
    VALUES(2, 'JOANA PEREIRA', 'AV PORTUGAL, 52', 'jpereira@novatec.com.br');

INSERT INTO COMPRADOR(CDCOMPRADOR, NMCOMPRADOR, NMENDERECO, EMAIL)
    VALUES(3, 'RONALDO CAMPELO', 'R ESTADO UNIDOS, 790', 'rcampleo@novatec.com.br');

INSERT INTO COMPRADOR(CDCOMPRADOR, NMCOMPRADOR, NMENDERECO, EMAIL)
    VALUES(4, 'MANFRED AUGUSTO', 'AV BRASIL, 351', 'maugusto@novatec.com.br');

INSERT INTO OFERTA(CDCOMPRADOR, CDIMOVEL, VLOFERTA, DTOFERTA)
    VALUES(1, 1, 170000, '10/01/02');

INSERT INTO OFERTA(CDCOMPRADOR, CDIMOVEL, VLOFERTA, DTOFERTA)
    VALUES(1, 3, 180000, '10/01/02');

INSERT INTO OFERTA(CDCOMPRADOR, CDIMOVEL, VLOFERTA, DTOFERTA)
    VALUES(2, 2, 135000, '15/02/02');

INSERT INTO OFERTA(CDCOMPRADOR, CDIMOVEL, VLOFERTA, DTOFERTA)
    VALUES(2, 4, 100000, '15/02/02');

INSERT INTO OFERTA(CDCOMPRADOR, CDIMOVEL, VLOFERTA, DTOFERTA)
    VALUES(3, 1, 160000, '05/01/02');

INSERT INTO OFERTA(CDCOMPRADOR, CDIMOVEL, VLOFERTA, DTOFERTA)
    VALUES(3, 2, 140000, '20/02/02');

--Atualaizando preço do imóvel aumentado o atributo VLPRECO em 10%
UPDATE IMOVEL 
    SET VLPRECO = VLPRECO * 1.1;

--Atualaizando preço do imóvel diminuinto o atributo VLPRECO em 5% quando for o vendedor 1
UPDATE IMOVEL
    SET VLPRECO= VLPRECO * .95
	WHERE CDVENDEDOR = 1;

--Atualaizando preço do imóvel aumentado o atributo VLOFERTA em 5% quando for o comprador 2
UPDATE OFERTA
    SET VLOFERTA = VLOFERTA * 1.05
	WHERE CDCOMPRADOR = 2;

--Atualaizando o endereço e o estado do comprador 3
UPDATE COMPRADOR
    SET NMENDERECO = 'R ANANAS, 45', SGESTADO= 'RJ'
	WHERE CDCOMPRADOR =3;

--Atualaizando oa oferta ao imovel 4 do comprador 2
UPDATE OFERTA 
    SET VLOFERTA = 101000
	WHERE CDCOMPRADOR = 2 AND CDIMOVEL = 4;


--Excluindo a oferta ao imovel 1 do comprador 3
DELETE FROM OFERTA 
    WHERE CDCOMPRADOR =3 AND CDIMOVEL = 1;

--Excluindo a cidade 3 do estado SP
DELETE FROM CIDADE 
    WHERE CDCIDADE = 3 AND SGESTADO = 'SP';

--Incluindo tuplas na entidade FAIXA_IMOVEL 
INSERT INTO FAIXA_IMOVEL (CDFAIXA, NMFAIXA, VLMINIMO, VLMAXIMO)
    VALUES(1, 'BAIXO', 0, 105000);

INSERT INTO FAIXA_IMOVEL (CDFAIXA, NMFAIXA, VLMINIMO, VLMAXIMO)
    VALUES(2, 'MÉDIO', 105001, 180000);

INSERT INTO FAIXA_IMOVEL (CDFAIXA, NMFAIXA, VLMINIMO, VLMAXIMO)
    VALUES(3, 'ALTO', 180001, 999999);
