USE ImovelNet

SELECT CDIMOVEL, NMEDERECO 
FROM IMOVEL 
WHERE CDBAIRRO = (SELECT CDBAIRRO 
FROM IMOVEL 
WHERE CDIMOVEL = 2) AND CDIMOVEL != 2

SELECT CDIMOVEL, NMEDERECO 
FROM IMOVEL 
WHERE VLPRECO > (SELECT AVG(VLPRECO) 
FROM IMOVEL) 

SELECT a.CDCOMPRADOR, NMCOMPRADOR, b.VLOFERTA 
FROM COMPRADOR a, OFERTA b
WHERE a.CDCOMPRADOR = b.CDCOMPRADOR AND
b.VLOFERTA > 70000

SELECT CDIMOVEL, CDCOMPRADOR, VLOFERTA
FROM OFERTA 
WHERE VLOFERTA > (SELECT AVG(VLOFERTA)
FROM OFERTA)

SELECT a.CDIMOVEL NMEDERECO, VLPRECO
FROM IMOVEL a 
WHERE VLPRECO > (SELECT AVG(VLPRECO)
FROM IMOVEL b 
WHERE a.CDBAIRRO = b.CDBAIRRO)

SELECT CDBAIRRO, AVG(VLPRECO) MÉDIA 
FROM IMOVEL
GROUP BY CDBAIRRO
HAVING MAX(VLPRECO) > (SELECT AVG(VLPRECO)
FROM IMOVEL)

SELECT CDIMOVEL, VLPRECO, a.CDVENDEDOR
FROM IMOVEL a
WHERE VLPRECO = (SELECT MIN(VLPRECO)
FROM IMOVEL b
WHERE a.CDVENDEDOR = b.CDVENDEDOR)

SELECT b.CDCOMPRADOR, a.DTLANCTO, a.CDIMOVEL
FROM IMOVEL a, OFERTA b 
WHERE a.CDIMOVEL = b.CDIMOVEL AND
a.DTLANCTO BETWEEN CURRENT_TIMESTAMP - 180
AND CURRENT_TIMESTAMP - 30
AND CDVENDEDOR = 2

SELECT CDIMOVEL, VLPRECO, NMEDERECO
FROM IMOVEL a
WHERE VLPRECO <= (SELECT MIN(VLPRECO)
FROM IMOVEL
WHERE CDVENDEDOR != a.CDVENDEDOR )

SELECT VLOFERTA, CDCOMPRADOR
FROM OFERTA 
WHERE VLOFERTA < (SELECT MAX(VLOFERTA) 
FROM OFERTA 
WHERE CDCOMPRADOR = 2)
AND CDCOMPRADOR !=2

SELECT CDIMOVEL, NMEDERECO
FROM IMOVEL 
WHERE (SGESTADO, CDCIDADE) IN (SELECT SGESTADO
FROM VENDEDOR 
WHERE CDVENDEDOR = 3) 
AND CDVENDEDOR !=3

SELECT NMBAIRRO
FROM BAIRRO
WHERE (SGESTADO, CDCIDADE, CDBAIRRO) IN (SELECT SGESTADO, CDBAIRRO, CDCIDADE
FROM IMOVEL
WHERE CDIMOVEL =5) 

