USE ImovelNet

SELECT CURRENT_TIMESTAMP

SELECT CDIMOVEL, VLPRECO, VLPRECO*1.1
FROM IMOVEL 

SELECT CDIMOVEL, VLPRECO, VLPRECO*1.1, VLPRECO*.1
FROM IMOVEL 

SELECT UPPER(NMVENDEDOR), LOWER(EMAIL)
FROM VENDEDOR;

SELECT CONCAT(NMCOMPRADOR,' - ', NMENDERECO)
FROM COMPRADOR;

SELECT NMCOMPRADOR
FROM COMPRADOR 
WHERE NMCOMPRADOR LIKE '%A%';

SELECT SUBSTRING(NMCOMPRADOR,1,1), NMBAIRRO
FROM COMPRADOR

SELECT CDIMOVEL, GETDATE() AS DataAtual,
DATEADD(DAY, -DATEDIFF(DAY, DTOFERTA, GETDATE()), GETDATE()) AS DataSubtraida
FROM OFERTA;