USE ImovelNet

SELECT MAX(VLOFERTA) MAIOR, MIN(VLOFERTA) MENOR, AVG(VLOFERTA) MEDIA
FROM OFERTA 

SELECT STDEV(VLPRECO) DESVIO_PADRAO, VAR(VLPRECO) VARINCIA 
FROM IMOVEL

SELECT CAST(STDEV(VLPRECO) AS DECIMAL (20,2)) DESVIO, CAST(VAR(VLPRECO) AS DECIMAL (20,2)) VARIANCIA
FROM IMOVEL

SELECT MAX(VLPRECO) MAXIMO, MIN(VLPRECO) MINIMO, SUM(VLPRECO) TOTAL, AVG(VLPRECO) MEDIA
FROM IMOVEL

SELECT MAX(VLPRECO) MAXIMO, MIN(VLPRECO) MINIMO, SUM(VLPRECO) TOTAL, AVG(VLPRECO) MEDIA, CDBAIRRO
FROM IMOVEL
GROUP BY CDBAIRRO

SELECT CDVENDEDOR, COUNT(*) TOTAL_DE_IMOVEIS
FROM IMOVEL
GROUP BY CDVENDEDOR
ORDER BY  COUNT(*)

SELECT MAX(VLPRECO) - MIN(VLPRECO) DIFERENÇA
FROM IMOVEL 

SELECT CDVENDEDOR, MIN(VLPRECO) MENOR_VALOR_IMOVEL
FROM IMOVEL
WHERE VLPRECO >= 10000
GROUP BY CDVENDEDOR

SELECT CDCOMPRADOR, AVG(VLOFERTA), COUNT(*)
FROM OFERTA
GROUP BY CDCOMPRADOR 

SELECT YEAR(DTOFERTA) AS ANO_OFERTA, COUNT(VLOFERTA) AS TOTAL_OFERTAS, CDCOMPRADOR
FROM OFERTA
WHERE YEAR(DTOFERTA) IN (2000, 2001, 2002)
GROUP BY YEAR(DTOFERTA), CDCOMPRADOR;